#! /bin/sh

rm assets/Resources
rm assets/tiapp.xml

R=/Users/dthorp/projects/appcelerator/ks_android_titanium_mobile/demos/KitchenSink
ln -s $R/Resources assets/Resources
ln -s $R/tiapp.xml assets/tiapp.xml
