
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by 
 * Appcelerator from the resource data it found.  It
 * should not be modified by hand.
 */

package org.appcelerator.kitchensink;

import java.util.HashMap;

public final class RA 
{

    private static final HashMap<String,Integer> _drawable = new HashMap<String,Integer>();
    private static final HashMap<String,Integer> _attr = new HashMap<String,Integer>();
    private static final HashMap<String,Integer> _string = new HashMap<String,Integer>();

    static {
        _drawable.put("appicon",0x7f020000);
        _drawable.put("background",0x7f020001);
        _string.put("controls_win_title",0x7f030004);
        _string.put("welcome_message",0x7f030000);
        _string.put("mashups_win_title",0x7f030007);
        _string.put("user_agent_message",0x7f030001);
        _string.put("platform_win_title",0x7f030006);
        _string.put("format_test",0x7f030002);
        _string.put("base_ui_title",0x7f030003);
        _string.put("phone_win_title",0x7f030005);

    }
    
    public static final Integer getDrawable(String key){
       return _drawable.get(key);
    }
    public static final Integer getAttr(String key){
       return _attr.get(key);
    }
    public static final Integer getString(String key){
       return _string.get(key);
    }
    
}